org.gradle.java.home=/Users/ggpark/Library/Java/JavaVirtualMachines/ms-17.0.17/Contents/Home
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
